language: python
python:
- '3.7'
- '3.8'
install:
- pip install --upgrade pip
- pip install -e .
- pip install -r test_requirements.txt
env:
- TEST_ENV=travis
after_success:
- coveralls
notifications:
  email:
    recipients:
    - blaiszik@uchicago.edu
    - mschwarting@anl.gov
    on_success: never
    on_failure: change
deploy:
  provider: pypi
  user: jgaff
  on:
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: 
