name: bubble-vis

on:
  push:
    branches:
      - main
      - bubble-vis

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update diagram
        uses: githubocto/repo-visualizer@0.3.0
        with:
          excluded_paths: "docs,.github"
