name: bubble-vis

on:
  push:
    branches:
      - main
      - bubble-vis

jobs:
  build:

  steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Update diagram
      uses: githubocto/repo-visualizer@0.3.0
