name: codecov

on:
  workflow_run:
    workflows: ["testing-work"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Generate coverage report
      run: |
        pip install pytest-cov
        pytest --cov=./foundry --cov-report=xml

    - name: Upload coverage to Codecov
      run: |
        curl -Os https://uploader.codecov.io/v0.1.0_4653/linux/codecov

        chmod +x codecov
        ./codecov -t ${{ secrets.CODECOV_TOKEN }}
